### ISSUE TITLE
Not finding lowest cost path

### ISSUE THREAD

**Issue by wvffle** [cpowell/cppGOAP#4]
So, let's say that we have 3 actions:

- `chopLogs`
  - cost: `4`
  - preconditions:
    - hasAxe: `true`
  - effects:
    - hasWood: `true`
- `getAxe`
  - cost: `1`
  - preconditions:
  - effects:
    - hasAxe: `true`
- `collectBranches`
  - cost: `8`
  - preconditions:
  - effects:
    - hasWood: `true`

Our goal is to get wood, so:
- hasWood: true

And our world state is something like this:
- hasWood: `false`
- hasAxe: `false`

And the planner will choose `collectBranches` (cost: 8) over `getAxe, chopLogs` (cost: 5)

**Comment by fdgngrpjk** [comment]
it works fine
`
int main(void) {
	std::cout << "T example running...\n";
	std::vector<Action> actions;

	// Constants for the various states are helpful to keep us from
	// accidentally mistyping a state name.
	const int hasAxe = 10;
	const int hasWood = 15;

	// Now establish all the possible actions for the action pool
	// In this example we're providing the AI some different FPS actions
	Action getAxe("getAxe", 1);
	getAxe.setEffect(hasAxe, true);
	actions.push_back(getAxe);

	Action chopLogs("chopLogs", 4);
	chopLogs.setPrecondition(hasAxe, true);
	chopLogs.setEffect(hasWood, true);
	actions.push_back(chopLogs);

	Action collectBranches("collectBranches", 8);
	collectBranches.setEffect(hasWood, true);
	actions.push_back(collectBranches);

	// Here's the initial state...
	WorldState initial_state;
	initial_state.setVariable(hasAxe, false);
	initial_state.setVariable(hasWood, false);

	// ...and the goal state
	WorldState get_wood;
	get_wood.setVariable(hasWood, true);
	get_wood.priority_ = 50;

	// Fire up the A* planner
	Planner as;
	try {
		std::vector<Action> the_plan = as.plan(initial_state, get_wood, actions);
		std::cout << "Found a path!\n";
		for (std::vector<Action>::reverse_iterator rit = the_plan.rbegin(); rit != the_plan.rend(); ++rit) {
			std::cout << rit->name() << std::endl;
		}
	}
	catch (const std::exception&) {
		std::cout << "Sorry, could not find a path!\n";
	}

}
`

**Comment by cpowell** [comment]
Confirmed working.
